spring.application.name=democlient
# Configure the default Eureka server URL for client registration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
server.port=8082
# Optional: Register the service using its IP address rather than hostname
eureka.instance.prefer-ip-address=true
